version: '3.1'

services:
  app:
    build: .
    command: bash -c "python /project/manage.py collectstatic -v0 --noinput && python /project/manage.py migrate --noinput && cd /project && gunicorn least.wsgi --bind=0.0.0.0:8000 --workers=3"
#    command: bash -c "python /project/manage.py collectstatic -v0 --noinput && python /project/manage.py migrate --noinput && python /project/manage.py runserver 0.0.0.0:8000"
    stdin_open: true
    tty: true
    restart: always
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: 'least.settings'
    volumes:
      - ./project:/project
      - ./static:/static

  nginx:
    build:
      ./nginx
    restart: always
    env_file:
      - nginx/.env
    ports:
      - "80:80"
    volumes:
      - ./static:/static